=== alexcogojocaru/an3_sem2/pw/persoane.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="persoane">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="persoana" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nume" type="xs:string"></xs:element>
                        <xs:element name="prenume" type="xs:string"></xs:element>
                        <xs:element name="varsta" type="xs:unsignedInt"></xs:element>
                    
                        <xs:element name="adresa">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="strada" type="xs:string"></xs:element>
                                    <xs:element name="numar" type="xs:unsignedInt"></xs:element>
                                    <xs:element name="localitate" type="xs:string"></xs:element>
                                    <xs:element name="judet" type="xs:string"></xs:element>
                                    <xs:element name="tara" type="xs:string"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <xs:element name="job">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="firma" type="xs:string"></xs:element>
                                    <xs:element name="rol" type="xs:string"></xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== alexcogojocaru/an3_sem2/pw/persoane.xml
<?xml version="1.0" encoding="UTF-8" ?>
<persoane 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="persoane.xsd">
    <persoana id="1">
        <nume>Popescu</nume>
        <prenume>Ion</prenume>
        <varsta>23</varsta>

        <adresa>
            <strada>Carol</strada>
            <numar>1</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>

        <job>
            <firma>Amazon</firma>
            <rol>Software Engineer</rol>
        </job>
    </persoana>

    <persoana id="2">
        <nume>George</nume>
        <prenume>Sorin</prenume>
        <varsta>20</varsta>

        <adresa>
            <strada>Aleea Noua</strada>
            <numar>9</numar>
            <localitate>Botosani</localitate>
            <judet>Botosani</judet>
            <tara>Romania</tara>
        </adresa>

        <job>
            <firma>Continental</firma>
            <rol>Software Developer</rol>
        </job>
    </persoana>

    <persoana id="3">
        <nume>Cojocaru</nume>
        <prenume>Alex</prenume>
        <varsta>21</varsta>

        <adresa>
            <strada>Ciurchi</strada>
            <numar>101</numar>
            <localitate>Iasi</localitate>
            <judet>Iasi</judet>
            <tara>Romania</tara>
        </adresa>

        <job>
            <firma>Continental</firma>
            <rol>Software Developer</rol>
        </job>
    </persoana>
</persoane>
